// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemoniArena.Models;

#nullable disable

namespace PokemoniArena.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20250320103546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PokemoniArena.Models.Souboj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HracJmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HracZivoty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KonecSouboje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtivnikJmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtivnikZivoty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Souboje");
                });
#pragma warning restore 612, 618
        }
    }
}
